#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    #    url: jdbc:mysql://localhost:3306/jookbiren_admin?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#    url: jdbc:mysql://${AWS_RDS_ENDPOINT}/episode1?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#    username: ${MYSQL_ROOT_NAME}
#    password: ${MYSQL_ROOT_PASSWORD}
spring:
  datasource:
    first_db:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/jookbiren_admin?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      username: ${MYSQL_ROOT_NAME}
      password: ${MYSQL_ROOT_PASSWORD}
    second_db:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${AWS_RDS_ENDPOINT}/episode1?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      username: ${SECOND_MYSQL_ROOT_NAME}
      password: ${SECOND_MYSQL_ROOT_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
